django_tutorial_cs50/frst/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("home/",include("home.urls")),
    path("newyear/",include("newyear.urls")),
    path("tasks/",include("tasks.urls"))
]

django_tutorial_cs50/home/urls.py
from django.urls import path # give ability to reroute urls
from . import views # import any functions we created in veiws

urlpatterns = [ # call path function ( A string representing the URL path, a function from views.py that we wish to call when that URL is visited, and (optionally) a name for that path, in the format name="something")
    path("",views.index, name="index"),
    path("<str:name>",views.greet,name="greet"),
]

django_tutorial_cs50/newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

django_tutorial_cs50/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("",views.index,name="index"),
    path("add",views.add,name="add")
]

django_tutorial_cs50/home/models.py
from django.db import models

# Create your models here.

django_tutorial_cs50/newyear/models.py
from django.db import models

# Create your models here.

django_tutorial_cs50/tasks/models.py
from django.db import models

# Create your models here.

django_tutorial_cs50/home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse("Hello, world!")

def greet(request,name:str):
    return render(request,"home/greet.html",{
        "name":name.capitalize()
    })

django_tutorial_cs50/newyear/views.py
from django.shortcuts import render
from datetime import datetime
# Create your views here.
def index(request):
    now  = datetime.now()
    return render(request,"newyear/index.html",{
        "newyear": now.month == 3 and now.day == 3
    })

django_tutorial_cs50/tasks/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
#tasks = ["foo","bar","baz"]

class NewTaskForm(forms.Form): # create forms for us
    task = forms.CharField(label="New Task")


# Create your views here.
def index(request):
    # exe in terminal python manage.py migrate to create django table that stores session
    if "tasks" not in request.session: #session: dict that have all data we have on file inside the session of user
        request.session["tasks"] = []
    return render(request,"tasks/index.html",{
        "tasks":request.session["tasks"],
    })

def add(request):
    if request.method == "POST": # if the user has submitted some form data
        form = NewTaskForm(request.POST) # save up all data they submitted
        if form.is_valid(): #server side validation
            task = form.cleaned_data["task"] #get the subimitted data
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request,"tasks/add.html",{
                "form":form
            })
    return render(request,"tasks/add.html",{
        "form":NewTaskForm()
    })

django_tutorial_cs50/home/templates/home/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello</title>
    </head>
    <body>
        <h1>Hello, {{ name }}!</h1>
        <!-- {{}} allow to use variables -->
    </body>
</html>

django_tutorial_cs50/newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Is it New Year's?</title>
        <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
    </head>
    <body>
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
    </body>
</html>

django_tutorial_cs50/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
<h1>Add Task:</h1>
<form action="{% url 'tasks:add' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>
<a href="{% url 'tasks:index' %}">Veiw tasks</a>
{% endblock %}

django_tutorial_cs50/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% empty %}
            <li>No Tasks.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasks:add' %}">Add a new Task</a> 
{% endblock %}

django_tutorial_cs50/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>